export const END_POINTS = {
    GET_WRITING_TEST: '/exam',
    SUBMIT_WRITING_TEST: '/exam/score',
    GET_ALL_TOPIC: '/topic/list',
    GET_ALL_WRITING_TEST: '/exam/writing/list',
    SAVE_WRITING_TEST: '/history',
    // INFO: auth
    LOGIN: '/public/login',
    GET_ALL_ADMIN_TOPIC: '/admin/topics',
    CREATE_QUESTION: '/card',
    GET_HISTORY: '/history/detail',
    CHECK_TOKEN: '/public/token',
    UPLOAD_FILE: '/upload',
    GET_ALL_CLASS: '/admin/classroom/list',
    GET_QUESTIONS: '/admin/cards',
    CREATE_EXAM: '/exam',
    GET_USER_IN_CLASS: '/admin/users',
    GET_EXAMS: '/admin/exams',
    GET_TOPICS: '/admin/topics',
    GET_TEACHERS: '/admin/users',
    GET_STAFF: '/admin/users',
}